name: e_commerce
description: "A new Flutter project."
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0' # Restrições de SDK

dependencies:
  flutter:
    sdk: flutter
  async: ^2.12.0
  characters: ^1.3.0
  collection: ^1.18.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  matcher: ^0.12.17
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.3
  vm_service: ^14.3.0
  sqflite: ^2.0.0+4  # Atualize para a versão mais recente, se necessário
  path_provider: ^2.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
  assets:
    - assets/images/ # Caminho da pasta onde estão suas imagens
